version: '3.7'
services:
  django:
    container_name: django_apps
    build: ./django_apps
    tty: true
    ports:
      - 8888:8000

  # python:
  #   build: .
  #   tty: true
  #   image: python
  #   container_name: python
  #   volumes:
  #     - ./:/usr/src/app
  #   environment:
  #     - CELERY_BROKER=redis://redis:6379/0
  #     - CELERY_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - redis

  celery:
    image: python:3.8-alpine
    tty: true
    container_name: celery
    # volumes:
    #   - ./:/usr/src/app
    #   - ./logs:/usr/src/app/logs
    # environment:
    #   - CELERY_BROKER=redis://redis:6379/0
    #   - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      # - python
    # command: celery -A tasks worker --loglevel=info  --logfile=logs/celery.log

  redis:
    image: redis:alpine
    container_name: redis
    tty: true
    ports:
      - 6370:6379

  monitor:
    image: python:3.8-alpine
    tty: true
    container_name: monitor
    ports:
      - 5555:5555
    depends_on:
      - redis
      # - python
    # command:  flower -A tasks --port=5555 --broker=redis://redis:6379/0
