version: '3.7'
services:
  redis:
    image: redis:alpine
    container_name: redis
    tty: true
    ports:
      - 6370:6379

  db:
    container_name: db
    image: postgres:12
    restart: always
    tty: true
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - 5430:5432

  django:
    container_name: django
    build: ./django
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./django:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "sh ./migrate.sh && python manage.py runserver 0:8000"

  celery:
    container_name: celery
    build: ./django
    tty: true
    volumes:
      - ./logs:/usr/src/app/logs
      # - ./:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      # - python
    # command: celery -A tasks worker --loglevel=info  --logfile=logs/celery.log

  monitor:
    container_name: monitor
    build: ./django
    tty: true
    ports:
      - 5555:5555
    depends_on:
      - redis
      # - python
    # command: flower -A tasks --port=5555 --broker=redis://redis:6370/0

  # python:
  #   build: .
  #   tty: true
  #   image: python
  #   container_name: python
  #   volumes:
  #     - ./:/usr/src/app
  #   environment:
  #     - CELERY_BROKER=redis://redis:6379/0
  #     - CELERY_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - redis

volumes:
  db_data:
